export const requestList = [
  {
    icon: "",
    iconStyles: "fi fi-rr-plan",
    menuTitle: "Academic Integrity Policy and Procedure",
    subTitle: "Standards for academic honesty.",
    slug: "academic-integrity-policy-and-procedure",
    link: "/assets/Policy-and-procedure/Academic-Integrity-Policy-and-Procedure.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-rr-graduation-cap",
    menuTitle: "Course Progression and Graduation Policy",
    subTitle: "Criteria for course completion.",
    slug: "course-progression-and-graduation-policy",
    link: "/assets/Policy-and-procedure/Course-Progression-an-Graduation-Policy.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-rr-book-bookmark",
    menuTitle: "Advanced Standing Policy and Procedure",
    subTitle: "Credits for prior learning.",
    slug: "advanced-standing-policy-and-procedure",
    link: "/assets/Policy-and-procedure/Advanced-Standing-Policy-and-Procedure.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-bs-shield",
    menuTitle: "Assessment Moderation Policy",
    subTitle: "Ensuring fair assessments.",
    slug: "assessment-moderation-policy",
    link: "/assets/Policy-and-procedure/AB5-Assessment-Moderation-Policy.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-ss-refund-alt",
    menuTitle: "Refund Policy",
    subTitle: "Conditions for fee refunds.",
    slug: "refund-policy",
    link: "/assets/Policy-and-procedure/Refund-Policy.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-br-handshake",
    menuTitle: "Student Code of Conduct",
    subTitle: "Behavioral expectations.",
    slug: "conduct-of-codeStudent",
    link: "/assets/Policy-and-procedure/Student-Code-of-Conduct.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-rr-student",
    menuTitle: "Student Grievance Management Policy",
    subTitle: "Handling student complaints.",
    slug: "student-grievance-management-policy",
    link: "/assets/Policy-and-procedure/Student-Grievance-Management-Policy.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-rr-leader-speech",
    menuTitle: "Student Consultation Policy",
    subTitle: "Guidelines for consultations.",
    slug: "student-consultation-policy",
    link: "/assets/Policy-and-procedure/Student-Consultation-Policy.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-rs-light-emergency-on",
    menuTitle: "Critical Incident and Emergency Management Policy",
    subTitle: "Emergency response procedures.",
    slug: "critical-incident-and-emergency-management-policy",
    link: "/assets/Policy-and-procedure/Critical-Incident-and-Emergency-Management-Policy-Parramatta.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-rr-employee-handbook",
    menuTitle: "Deferral Suspension and Cancellation Policy and Procedure",
    subTitle: "Policies for course changes.",
    slug: "deferral-suspension-and-cancellation-policy-and-procedure",
    link: "/assets/Policy-and-procedure/Deferral-Suspension-and-Cancellation-Policy-and-Procedure.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-rr-plane-departure",
    menuTitle: "International Student Transfer Policy and Procedure",
    subTitle: "Transfer guidelines for students.",
    slug: "international-student-transfer-policy-and-procedure",
    link: "/assets/Policy-and-procedure/International-Student-Transfer-Policy-and-Procedure.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-rr-book-arrow-right",
    menuTitle: "Course Discontinuation and Teach Out Policy",
    subTitle: "Procedures for course end.",
    slug: "course-discontinuation-and-teach-out-policy",
    link: "/assets/Policy-and-procedure/Course-Discontinuation-and-Teach-Out-Policy_v1.1.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-rs-employee-man-alt",
    menuTitle: "New Student Orientation Policy",
    subTitle: "Orientation procedures.",
    slug: "new-student-orientation-policy",
    link: "/assets/Policy-and-procedure/New-Studen-Orientatio-Policy.pdf",
  },
  {
    icon: "",
    iconStyles: "fi fi-rr-clipboard",
    menuTitle: "Policy Assessment",
    subTitle: "Evaluation of policies.",
    slug: "policy-assessment",
    link: "/assets/Policy-and-procedure/AB6-Assessment-Policy.pdf",
  },
  {
    iconStyles: "fi fi-rr-onboarding",
    menuTitle: "Student Support Policy",
    subTitle: "Support for Churchill students.",
    slug: "student-support-policy",
    link: "/assets/Policy-and-procedure/SupportforStudentsPolicy.pdf",
  },
];
