export const staffDirectoryData = [
  {
    order: 1,
    title: "Michael Seamer",
    department: "student support team",
    image: "/assets/news-banner.png",
    number: "+61298765432",
    email: "michael-seamer@churchill.nsw.edu.au",
    position: "Professor",
  },
  {
    order: 2,
    title: "Dhitika Bansal",
    department: "it support team",
    image: "/assets/news-banner.png",
    number: "+61287654321",
    email: "dhitika-bansal@churchill.nsw.edu.au",
    position: "IT Specialist",
  },
  {
    order: 3,
    title: "Asmita KHATRI",
    department: "academics team",
    image: "/assets/news-banner.png",
    number: "+61276543210",
    email: "asmita-khatri@churchill.nsw.edu.au",
    position: "Lecturer",
  },
  {
    order: 4,
    title: "Shivang Jaiswal",
    department: "finance team",
    image: "/assets/news-banner.png",
    number: "+61265432109",
    email: "shivang-jaiswal@churchill.nsw.edu.au",
    position: "Accountant",
  },
  {
    order: 5,
    title: "Dr Siddharth Jain",
    department: "academics team",
    image: "/assets/news-banner.png",
    number: "+61254321098",
    email: "siddharth-jain@churchill.nsw.edu.au",
    position: "Senior Lecturer",
  },
  {
    order: 6,
    title: "Agency Support",
    department: "student support team",
    image: "/assets/news-banner.png",
    number: "+61243210987",
    email: "agency-support@churchill.nsw.edu.au",
    position: "Support Staff",
  },
  {
    order: 7,
    title: "Shreejana Khatri",
    department: "it support team",
    image: "/assets/news-banner.png",
    number: "+61232109876",
    email: "shreejana-khatri@churchill.nsw.edu.au",
    position: "IT Support",
  },
  {
    order: 8,
    title: "Sanjay LAMA",
    department: "finance team",
    image: "/assets/news-banner.png",
    number: "+61221098765",
    email: "sanjay-lama@churchill.nsw.edu.au",
    position: "Financial Analyst",
  },
  {
    order: 9,
    title: "Dr Tom Denigan",
    department: "academics team",
    image: "/assets/news-banner.png",
    number: "+61210987654",
    email: "tom-denigan@churchill.nsw.edu.au",
    position: "Professor",
  },
  {
    order: 10,
    title: "Student Support",
    department: "student support team",
    image: "/assets/news-banner.png",
    number: "+61209876543",
    email: "student-support@churchill.nsw.edu.au",
    position: "Counselor",
  },
  {
    order: 11,
    title: "Dr Prabhu Jyot Singh",
    department: "academics team",
    image: "/assets/news-banner.png",
    number: "+61298765432",
    email: "prabhu-jyot-singh@churchill.nsw.edu.au",
    position: "Researcher",
  },
  {
    order: 12,
    title: "Rohit Saini",
    department: "it support team",
    image: "/assets/news-banner.png",
    number: "+61287654321",
    email: "rohit-saini@churchill.nsw.edu.au",
    position: "IT Manager",
  },
];
