export const UpcomingKeyData = {
  2024: {
    January: [],
    February: [],
    March: [],
    April: [],
    May: [
      {
        id: 1,
        title: "Continuing Student Enrolment Commences",
        slug: "continuing-student-enrolment-commences",
        linik: "",
        subTitle:
          "The enrolment period for continuing students begins, allowing them to register for the upcoming semester's classes and ensure their spots in preferred courses.",
        image: "/assets/upcoming-key.png",
        fullDate: "2024/05/20",
        year: "2024",
        day: "SUN",
        date: "20",
        month: "May",
        displayMonth: "MAY",
        time: "7:00 AM to 11:00 AM",
        audiences: ["Staff"],
        categories: ["Days-of-Interest"],
      },
    ],
    June: [
      {
        id: 3,
        title: "Summer Session Orientation",
        slug: "summer-session-orientation",
        linik: "",
        subTitle:
          "Orientation event for new students enrolling in the summer session, providing essential information and resources to help them start their academic journey.",
        image: "/assets/upcoming-key.png",
        fullDate: "2024/06/10",
        year: "2024",
        day: "WED",
        date: "10",
        month: "June",
        displayMonth: "JUN",
        time: "9:00 AM to 3:00 PM",
        audiences: ["Student"],
        categories: ["Days-of-Interest"],
      },
    ],
    July: [
      {
        id: 2,
        title: "Fall Semester Registration Begins",
        slug: "fall-semester-registration-begins",
        linik: "",
        subTitle:
          "Registration for the fall semester opens, enabling students to sign up for courses and complete any necessary administrative tasks.",
        image: "/assets/upcoming-key.png",
        fullDate: "2024/07/15",
        year: "2024",
        day: "MON",
        date: "15",
        month: "July",
        displayMonth: "JUL",
        time: "8:00 AM to 5:00 PM",
        audiences: ["Postgraduate", "Student"],
        categories: ["Summer-Term-Dates", "Days-of-Interest"],
      },
    ],
    August: [
      {
        id: 7,
        title: "Faculty Development Workshop",
        slug: "faculty-development-workshop",
        linik: "",
        subTitle:
          "Workshop designed for faculty members to enhance teaching methodologies and stay updated on the latest trends in education.",
        image: "/assets/upcoming-key.png",
        fullDate: "2024/08/18",
        year: "2024",
        day: "TUE",
        date: "18",
        month: "August",
        displayMonth: "AUG",
        time: "1:00 PM to 4:00 PM",
        audiences: ["Faculty"],
        categories: ["Professional-Development", "Days-of-Interest"],
      },
    ],
    September: [
      {
        id: 4,
        title: "Mid-Term Exams",
        slug: "mid-term-exams",
        linik: "",
        subTitle:
          "Mid-term examinations for various courses, assessing students' understanding and knowledge gained during the first half of the semester.",
        image: "/assets/upcoming-key.png",
        fullDate: "2024/09/23",
        year: "2024",
        day: "THU",
        date: "23",
        month: "September",
        displayMonth: "SEP",
        time: "8:00 AM to 6:00 PM",
        audiences: ["Undergraduate"],
        categories: ["Semester-Dates"],
      },
      {
        id: 8,
        title: "Alumni Homecoming Weekend",
        slug: "alumni-homecoming-weekend",
        linik: "",
        subTitle:
          "Annual event inviting alumni back to campus to reconnect with former classmates, faculty, and staff.",
        image: "/assets/upcoming-key.png",
        fullDate: "2024/09/20",
        year: "2024",
        day: "FRI",
        date: "20",
        month: "September",
        displayMonth: "SEP",
        time: "",
        audiences: ["Alumni", "Staff"],
        categories: ["Days-of-Interest"],
      },
    ],
    October: [],
    November: [
      {
        id: 6,
        title: "Graduate Thesis Defense",
        slug: "graduate-thesis-defense",
        linik: "",
        subTitle:
          "Presentation and defense of graduate theses by postgraduate students, marking the culmination of their research work.",
        image: "/assets/upcoming-key.png",
        fullDate: "2024/11/07",
        year: "2024",
        day: "THU",
        date: "7",
        month: "November",
        displayMonth: "NOV",
        time: "9:00 AM to 5:00 PM",
        audiences: ["Postgraduate"],
        categories: ["Semester-Dates"],
      },
    ],
    December: [
      {
        id: 5,
        title: "Graduation Ceremony",
        slug: "graduation-ceremony",
        linik: "",
        subTitle:
          "Commencement ceremony for graduates, celebrating the completion of their academic programs and their achievements.",
        image: "/assets/upcoming-key.png",
        fullDate: "2024/12/05",
        year: "2024",
        day: "SAT",
        date: "5",
        month: "December",
        displayMonth: "DEC",
        time: "10:00 AM to 1:00 PM",
        audiences: ["Staff"],
        categories: ["Winter-Term-Dates", "Semester-Dates"],
      },
    ],
  },
  2023: {
    January: [
      {
        id: 1,
        title: "Continuing Student Enrolment Commences",
        slug: "continuing-student-enrolment-commences",
        linik: "",
        subTitle:
          "The enrolment period for continuing students begins, allowing them to register for the upcoming semester's classes and ensure their spots in preferred courses.",
        image: "/assets/upcoming-key.png",
        fullDate: "2024/05/20",
        year: "2024",
        day: "SUN",
        date: "20",
        month: "May",
        displayMonth: "MAY",
        time: "7:00 AM to 11:00 AM",
        audiences: ["Staff"],
        categories: ["Days-of-Interest"],
      },
    ],
    February: [],
    March: [],
    April: [
      {
        id: 2,
        title: "Fall Semester Registration Begins",
        slug: "fall-semester-registration-begins",
        linik: "",
        subTitle:
          "Registration for the fall semester opens, enabling students to sign up for courses and complete any necessary administrative tasks.",
        image: "/assets/upcoming-key.png",
        fullDate: "2024/07/15",
        year: "2024",
        day: "MON",
        date: "15",
        month: "July",
        displayMonth: "JUL",
        time: "8:00 AM to 5:00 PM",
        audiences: ["Postgraduate", "Student"],
        categories: ["Summer-Term-Dates", "Days-of-Interest"],
      },
    ],
    May: [],
    June: [],
    July: [],
    August: [],
    September: [
      {
        id: 8,
        title: "Alumni Homecoming Weekend",
        slug: "alumni-homecoming-weekend",
        linik: "",
        subTitle:
          "Annual event inviting alumni back to campus to reconnect with former classmates, faculty, and staff.",
        image: "/assets/upcoming-key.png",
        fullDate: "2024/09/20",
        year: "2024",
        day: "FRI",
        date: "20",
        month: "September",
        displayMonth: "SEP",
        time: "",
        audiences: ["Alumni", "Staff"],
        categories: ["Days-of-Interest"],
      },
    ],
    October: [],
    November: [
      {
        id: 6,
        title: "Graduate Thesis Defense",
        slug: "graduate-thesis-defense",
        linik: "",
        subTitle:
          "Presentation and defense of graduate theses by postgraduate students, marking the culmination of their research work.",
        image: "/assets/upcoming-key.png",
        fullDate: "2024/11/07",
        year: "2024",
        day: "THU",
        date: "7",
        month: "November",
        displayMonth: "NOV",
        time: "9:00 AM to 5:00 PM",
        audiences: ["Postgraduate"],
        categories: ["Semester-Dates"],
      },
    ],
    December: [],
  },
};

// export const UpcomingKeyData = [
//   {
//     id: 1,
//     title: "Continuing Student Enrolment Commences",
//     slug: "continuing-student-enrolment-commences",
//     linik: "",
//     subTitle:
//       "The enrolment period for continuing students begins, allowing them to register for the upcoming semester's classes and ensure their spots in preferred courses.",
//     image: "/assets/upcoming-key.png",

//     fullDate: "2024/05/20",
//     year: "2024",
//     day: "SUN",
//     date: "20",
//     month: "May",
//     displayMonth: "MAY",

//     time: "7:00 AM to 11:00 AM",
//     audiences: ["Staff"],
//     categories: ["Days-of-Interest"],
//   },
//   {
//     id: 2,
//     title: "Fall Semester Registration Begins",
//     slug: "fall-semester-registration-begins",
//     linik: "",
//     subTitle:
//       "Registration for the fall semester opens, enabling students to sign up for courses and complete any necessary administrative tasks.",
//     image: "/assets/upcoming-key.png",

//     fullDate: "2024/07/15",
//     year: "2024",
//     day: "MON",
//     date: "15",
//     month: "July",
//     displayMonth: "JUL",

//     time: "8:00 AM to 5:00 PM",
//     audiences: ["Postgraduate", "Student"],
//     categories: ["Summer-Term-Dates", "Days-of-Interest"],
//   },
//   {
//     id: 3,
//     title: "Summer Session Orientation",
//     slug: "summer-session-orientation",
//     linik: "",
//     subTitle:
//       "Orientation event for new students enrolling in the summer session, providing essential information and resources to help them start their academic journey.",
//     image: "/assets/upcoming-key.png",

//     fullDate: "2024/06/10",
//     year: "2024",
//     day: "WED",
//     date: "10",
//     month: "June",
//     displayMonth: "JUN",

//     time: "9:00 AM to 3:00 PM",
//     audiences: ["Student"],
//     categories: ["Days-of-Interest"],
//   },
//   {
//     id: 4,
//     title: "Mid-Term Exams",
//     slug: "mid-term-exams",
//     linik: "",
//     subTitle:
//       "Mid-term examinations for various courses, assessing students' understanding and knowledge gained during the first half of the semester.",
//     image: "/assets/upcoming-key.png",

//     fullDate: "2024/09/23",
//     year: "2024",
//     day: "THU",
//     date: "23",
//     month: "September",
//     displayMonth: "SEP",

//     time: "8:00 AM to 6:00 PM",
//     audiences: ["Undergraduate"],
//     categories: ["Semester-Dates"],
//   },
//   {
//     id: 5,
//     title: "Graduation Ceremony",
//     slug: "graduation-ceremony",
//     linik: "",
//     subTitle:
//       "Commencement ceremony for graduates, celebrating the completion of their academic programs and their achievements.",
//     image: "/assets/upcoming-key.png",

//     fullDate: "2024/12/05",
//     year: "2024",
//     day: "SAT",
//     date: "5",
//     month: "December",
//     displayMonth: "DEC",

//     time: "10:00 AM to 1:00 PM",
//     audiences: ["Staff"],
//     categories: ["Winter-Term-Dates", "Semester-Dates"],
//   },
//   {
//     id: 6,
//     title: "Graduate Thesis Defense",
//     slug: "graduate-thesis-defense",
//     linik: "",
//     subTitle:
//       "Presentation and defense of graduate theses by postgraduate students, marking the culmination of their research work.",
//     image: "/assets/upcoming-key.png",

//     fullDate: "2024/11/07",
//     year: "2024",
//     day: "THU",
//     date: "7",
//     month: "November",
//     displayMonth: "NOV",

//     time: "9:00 AM to 5:00 PM",
//     audiences: ["Postgraduate"],
//     categories: ["Semester-Dates"],
//   },
//   {
//     id: 7,
//     title: "Faculty Development Workshop",
//     slug: "faculty-development-workshop",
//     linik: "",
//     subTitle:
//       "Workshop designed for faculty members to enhance teaching methodologies and stay updated on the latest trends in education.",
//     image: "/assets/upcoming-key.png",

//     fullDate: "2024/08/18",
//     year: "2024",
//     day: "TUE",
//     date: "18",
//     month: "August",
//     displayMonth: "AUG",

//     time: "1:00 PM to 4:00 PM",
//     audiences: ["Faculty"],
//     categories: ["Professional-Development", "Days-of-Interest"],
//   },
//   {
//     id: 8,
//     title: "Alumni Homecoming Weekend",
//     slug: "alumni-homecoming-weekend",
//     linik: "",
//     subTitle:
//       "Annual event inviting alumni back to campus to reconnect with former classmates, faculty, and staff.",
//     image: "/assets/upcoming-key.png",

//     fullDate: "2024/09/20",
//     year: "2024",
//     day: "FRI",
//     date: "20",
//     month: "September",
//     displayMonth: "SEP",

//     time: "",
//     audiences: ["Alumni", "Staff"],
//     categories: ["Days-of-Interest"],
//   },
// ];
