export const UpcomingKeyData = [
    {
      title: "Continuing Student Enrolment Commences hello Continuing Student Enrolment Commences",
      slug: "continuing-student-enrolment-commences-hello-continuing-student-enrolment-commences",
      linik:'',
      subTitle: "Continuing Student Enrolment Commences",
      image:'/assets/upcoming-key.png',
      day:'SUN',
      date:'20',
      month:'MAY',
      time:'7:00 AM to 11:00 AM',
      Catagories: [],
    },
    {
      title: "Continuing Student Enrolment Commences hello Continuing Student Enrolment Commences",
      slug: "continuing-student-enrolment-commences-hello-continuing-student-enrolment-commences",
      linik:'',
      subTitle: "Continuing Student Enrolment Commences",
      image:'/assets/upcoming-key.png',
      day:'SUN',
      date:'20',
      month:'MAY',
      time:'7:00 AM to 11:00 AM',
      Catagories: [],
    },
    {
      title: "Continuing Student Enrolment Commences hello Continuing Student Enrolment Commences",
      slug: "continuing-student-enrolment-commences-hello-continuing-student-enrolment-commences",
      linik:'',
      subTitle: "Continuing Student Enrolment Commences",
      image:'/assets/upcoming-key.png',
      day:'SUN',
      date:'20',
      month:'MAY',
      time:'7:00 AM to 11:00 AM',
      Catagories: [],
    },
    {
      title: "Continuing Student Enrolment Commences hello Continuing Student Enrolment Commences",
      slug: "continuing-student-enrolment-commences-hello-continuing-student-enrolment-commences",
      linik:'',
      subTitle: "Continuing Student Enrolment Commences",
      image:'/assets/upcoming-key.png',
      day:'SUN',
      date:'20',
      month:'MAY',
      time:'7:00 AM to 11:00 AM',
      Catagories: [],
    },
  ];
  