export const usefulLinksData = [
  {
    icon: "/assets/canvas-icon.png",
    title: "Student Canvas Login",
    slug: "student-canvas-login",
    linik:'',
    subTitle: "Access your timetable, results, trimester invoices.",
    Catagories: [],
  },
  {
    icon: "/assets/student-portal-icon.png",
    title: "Student Email login",
    slug: "student-email-login",
    linik:'',
    subTitle: "Access your timetable, results, trimester invoices.",
    Catagories: [],
  },
  {
    icon: "/assets/office-icon.png",
    title: "Office365 Password Reset",
    slug: "office365-password-reset",
    linik:'',
    subTitle: "Access your timetable, results, trimester invoices.",
    Catagories: [],
  },
  {
    icon: "/assets/usi-icon.png",
    title: "Get Your Student USI",
    slug: "get-your-student-USI",
    linik:'',
    subTitle: "Access your timetable, results, trimester invoices.",
    Catagories: [],
  },
  {
    icon: "/assets/usi-icon.png",
    title: "Get Your Student USI",
    slug: "get-your-student-USI",
    linik:'',
    subTitle: "Access your timetable, results, trimester invoices.",
    Catagories: [],
  },
  {
    icon: "/assets/usi-icon.png",
    title: "Get Your Student USI",
    slug: "get-your-student-USI",
    linik:'',
    subTitle: "Access your timetable, results, trimester invoices.",
    Catagories: [],
  },
  {
    icon: "/assets/usi-icon.png",
    title: "Get Your Student USI",
    slug: "get-your-student-USI",
    linik:'',
    subTitle: "Access your timetable, results, trimester invoices.",
    Catagories: [],
  },
  {
    icon: "/assets/usi-icon.png",
    title: "Get Your Student USI",
    slug: "get-your-student-USI",
    linik:'',
    subTitle: "Access your timetable, results, trimester invoices.",
    Catagories: [],
  },
];
